version: "3.9"

services:

  # сервис для сборки проекта на хостинге
  jsm:
    profiles: [ jsm ]
    extends:
      service: jsm
      file: jsm/docker-compose.yml
    env_file: [ .env.production ]

  web:
    profiles: [ web ]
    build: ./nginx
    restart: unless-stopped
    hostname: web${suffix}
    container_name: web${suffix}
    env_file: [ .env, .env.production ]
    environment:
      - app_int_port
    ports:
      # публикация фронтенда
      - ${app_ext_port:-8080}:${app_int_port:-8080}

    networks:
      - compose-net

    volumes:
      - ./nginx/.bash_history:/root/.bash_history
      - ./.bashrc:/root/.bashrc

      # история команд, для отладки
      - type: bind
        source: ./nginx/.bash_history
        target: /home/appuser/.bash_history

      # настройки пользователя внутри контейнера, для отладки
      - type: bind
        source: .bashrc
        target: /home/appuser/.bashrc

        # папка со сборкой фронта
      - type: bind
        source: ./dist
        target: /home/appuser/src/app/dist

networks:
  compose-net:
    name: $NET_NAME
